In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [16]:
def matrix_addition(A, B):
    """
    Performs addition of two matrices
    
    Parameters:
    A (list of lists or numpy.ndarray): The first matrix
    B (list of lists or numpy.ndarray): The second matrix
    
    Returns:
    numpy.ndarray: The result of addition A + B
    """
    # Convert to numpy arrays
    A = np.array(A)
    B = np.array(B)
    
    # Verify that matrices are the same size
    if A.shape != B.shape:
        raise ValueError("Matrices must be the same size for addition")
    
    # Perform addition
    return A + B  # __add__

def matrix_subtraction(A, B):
    """
    Performs subtraction of two matrices
    
    Parameters:
    A (list of lists or numpy.ndarray): The first matrix
    B (list of lists or numpy.ndarray): The second matrix
    
    Returns:
    numpy.ndarray: The result of subtraction A - B
    """
    # Convert to numpy arrays
    A = np.array(A)
    B = np.array(B)
    
    # Verify that matrices are the same size
    if A.shape != B.shape:
        raise ValueError("Matrices must be the same size for subtraction")
    
    # Perform subtraction
    return A - B

def matrix_multiplication(A, B):
    """
    Performs multiplication of two matrices
    
    Parameters:
    A (list of lists or numpy.ndarray): The first matrix
    B (list of lists or numpy.ndarray): The second matrix
    
    Returns:
    numpy.ndarray: The result of multiplication A @ B
    """
    # Convert to numpy arrays
    A = np.array(A)
    B = np.array(B)
    
    # Verify that the number of columns in A equals the number of rows in B
    if A.shape[1] != B.shape[0]:
        raise ValueError("The number of columns in the first matrix must equal the number of rows in the second matrix")
    
    # Perform multiplication
    return A @ B  # or np.matmul(A, B)

# Define example matrices
A = [[4, 1, 7], [2, 8, 3], [5, 9, 0]]
B = [[2, 6, 1], [7, 0, 5], [3, 4, 9]]

print("Matrix A:")
for row in A:
    print(row)

print("\nMatrix B:")
for row in B:
    print(row)

print()

# Addition
result_addition = matrix_addition(A, B)
print("Matrix addition:")
print(result_addition)

C = [[8, 2], [5, 7], [3, 9]]
D = [[1, 4], [6, 2], [0, 5]]

# Subtraction
result_subtraction = matrix_subtraction(C, D)
print("\nMatrix subtraction:")
print(result_subtraction)

E = [[2, 0, 3, 1], [4, 5, 2, 7], [1, 3, 6, 2]]
F = [[3, 1, 2], [0, 4, 6], [7, 2, 5], [1, 8, 3]]

# Multiplication
result_multiplication = matrix_multiplication(E, F)
print("\nMatrix multiplication:")
print(result_multiplication)

G = [[5, 2, 8, 4], [1, 7, 3, 9], [6, 0, 5, 2], [3, 8, 1, 7]]

# Transpose
print("\nMatrix transpose:")
g_array = np.array(G)
g_transpose = g_array.T
print(g_transpose)

Matrix A:
[4, 1, 7]
[2, 8, 3]
[5, 9, 0]

Matrix B:
[2, 6, 1]
[7, 0, 5]
[3, 4, 9]

Matrix addition:
[[ 6  7  8]
 [ 9  8  8]
 [ 8 13  9]]

Matrix subtraction:
[[ 7 -2]
 [-1  5]
 [ 3  4]]

Matrix multiplication:
[[28 16 22]
 [33 84 69]
 [47 41 56]]

Matrix transpose:
[[5 1 6 3]
 [2 7 0 8]
 [8 3 5 1]
 [4 9 2 7]]
